<?php
/**
 * Registers the top-level "LD Schema" settings page.
 *
 * Administrators can enable or disable the meta box per public post type and
 * opt into strict JSON-LD removal. Settings are stored with the Settings API.
 *
 * @package Custom_LD_Schema
 */

defined( 'ABSPATH' ) || exit;

class LD_Schema_Settings {

	/**
	 * Register admin hooks.
	 */
	public function init() {
		add_action( 'admin_menu', array( $this, 'add_menu_page' ) );
		add_action( 'admin_init', array( $this, 'register_settings' ) );
	}

	/**
	 * Create the top-level admin menu.
	 */
	public function add_menu_page() {
		add_menu_page(
			__( 'LD Schema', 'custom-ld-schema' ),
			__( 'LD Schema', 'custom-ld-schema' ),
			'manage_options',
			LD_SCHEMA_SETTINGS_PAGE,
			array( $this, 'render_page' ),
			'dashicons-code-standards',
			80
		);
	}

	/**
	 * Register settings, sections and fields with the Settings API.
	 */
	public function register_settings() {
		register_setting(
			'ld_schema_settings_group',
			LD_SCHEMA_OPTION_POST_TYPES,
			array(
				'type'              => 'array',
				'default'           => array( 'post', 'page' ),
				'sanitize_callback' => array( $this, 'sanitize_post_types' ),
			)
		);

		register_setting(
			'ld_schema_settings_group',
			LD_SCHEMA_OPTION_STRICT_MODE,
			array(
				'type'              => 'boolean',
				'default'           => false,
				'sanitize_callback' => array( $this, 'sanitize_boolean' ),
			)
		);

		add_settings_section(
			'ld_schema_section_post_types',
			__( 'Post Types', 'custom-ld-schema' ),
			array( $this, 'render_post_types_section' ),
			LD_SCHEMA_SETTINGS_PAGE
		);

		add_settings_field(
			'ld_schema_field_post_types',
			__( 'Enable the LD Schema meta box for', 'custom-ld-schema' ),
			array( $this, 'render_post_types_field' ),
			LD_SCHEMA_SETTINGS_PAGE,
			'ld_schema_section_post_types'
		);

		add_settings_field(
			'ld_schema_field_strict_mode',
			__( 'Strict removal', 'custom-ld-schema' ),
			array( $this, 'render_strict_mode_field' ),
			LD_SCHEMA_SETTINGS_PAGE,
			'ld_schema_section_post_types'
		);
	}

	/**
	 * Section intro text.
	 */
	public function render_post_types_section() {
		echo '<p>' . esc_html__( 'Select the public post types where the LD Schema meta box should appear in the editor.', 'custom-ld-schema' ) . '</p>';
	}

	/**
	 * Render the post type checkboxes.
	 */
	public function render_post_types_field() {
		$current    = ld_schema_enabled_post_types();
		$post_types = ld_schema_get_public_post_types();

		echo '<fieldset>';

		foreach ( $post_types as $post_type => $object ) {
			$field_id = 'ld-schema-post-type-' . $post_type;
			$checked  = checked( in_array( $post_type, $current, true ), true, false );

			printf(
				'<label for="%1$s"><input type="checkbox" id="%1$s" name="%2$s[]" value="%3$s"%4$s /> %5$s</label><br />',
				esc_attr( $field_id ),
				esc_attr( LD_SCHEMA_OPTION_POST_TYPES ),
				esc_attr( $post_type ),
				$checked, // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- checked() output is safe.
				esc_html( $object->labels->name )
			);
		}

		echo '</fieldset>';
	}

	/**
	 * Render the strict removal checkbox.
	 */
	public function render_strict_mode_field() {
		$checked = checked( (bool) get_option( LD_SCHEMA_OPTION_STRICT_MODE, 0 ), true, false );

		printf(
			'<label for="ld-schema-strict-mode"><input type="checkbox" id="ld-schema-strict-mode" name="%1$s" value="1"%2$s /> %3$s</label>',
			esc_attr( LD_SCHEMA_OPTION_STRICT_MODE ),
			$checked, // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- checked() output is safe.
			esc_html__( 'Remove all other JSON-LD scripts generated by SEO plugins when a custom schema exists.', 'custom-ld-schema' )
		);
	}

	/**
	 * Render the settings page.
	 */
	public function render_page() {
		if ( ! current_user_can( 'manage_options' ) ) {
			return;
		}

		echo '<div class="wrap">';
		echo '<h1>' . esc_html( get_admin_page_title() ) . '</h1>';
		echo '<p>' . esc_html__( 'When a custom schema is saved for a page, it replaces the JSON-LD normally generated by SEO plugins so that exactly one schema block is output.', 'custom-ld-schema' ) . '</p>';

		settings_errors();

		echo '<form method="post" action="options.php">';
		settings_fields( 'ld_schema_settings_group' );
		do_settings_sections( LD_SCHEMA_SETTINGS_PAGE );
		submit_button();
		echo '</form>';
		echo '</div>';
	}

	/**
	 * Sanitize the post type checkboxes against the list of public post types.
	 *
	 * @param mixed $value Submitted checkbox values.
	 * @return string[]
	 */
	public function sanitize_post_types( $value ) {
		if ( ! is_array( $value ) ) {
			return array();
		}

		$valid_post_types = array_keys( ld_schema_get_public_post_types() );
		$sanitized        = array();

		foreach ( $value as $post_type ) {
			$post_type = sanitize_key( $post_type );

			if ( in_array( $post_type, $valid_post_types, true ) ) {
				$sanitized[] = $post_type;
			}
		}

		return $sanitized;
	}

	/**
	 * Sanitize a boolean checkbox value.
	 *
	 * @param mixed $value Submitted value.
	 * @return int
	 */
	public function sanitize_boolean( $value ) {
		return ! empty( $value ) ? 1 : 0;
	}
}
